# Generated by Django 5.0.7 on 2024-08-05 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_user_address_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='bs',
            field=models.CharField(default='target end-to-end models', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='catchPhrase',
            field=models.CharField(default='Centralized empowering task-force', max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.company'),
        ),
    ]
