# Generated by Django 5.0.7 on 2024-08-05 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_company_bs_company_catchphrase_alter_user_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='postId',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='album',
            new_name='albumId',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='userId',
        ),
    ]
