# Generated by Django 5.0.7 on 2024-08-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_post_comment_postid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(),
        ),
    ]
