# Generated by Django 5.0.7 on 2024-08-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_photo_thumbnailurl_alter_user_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='suite',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lng',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=200),
        ),
    ]
