# Generated by Django 5.0.7 on 2024-08-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_address_city_alter_address_suite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='userId',
        ),
    ]
