# Generated by Django 5.0.7 on 2024-08-05 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_rename_user_post_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='albumId',
            new_name='album',
        ),
    ]
