# Generated by Django 5.0.7 on 2024-08-05 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_rename_albumid_photo_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='userId',
        ),
    ]
