# Generated by Django 5.0.7 on 2024-08-06 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_photo_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='userId',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='userId',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='postId',
        ),
        migrations.RemoveField(
            model_name='company',
            name='bs',
        ),
        migrations.RemoveField(
            model_name='company',
            name='catchPhrase',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='myapp.geo'),
        ),
        migrations.AlterField(
            model_name='address',
            name='suite',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lng',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='photo',
            name='url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.URLField(),
        ),
    ]
