# Generated by Django 5.0.7 on 2024-08-06 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_rename_userid_album_user_rename_userid_post_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user',
            new_name='userId',
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='user',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='post',
        ),
        migrations.AddField(
            model_name='comment',
            name='postId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='myapp.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='bs',
            field=models.CharField(default='target end-to-end models', max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='catchPhrase',
            field=models.CharField(default='Centralized empowering task-force', max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='geo',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='myapp.geo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='suite',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='comment',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lat',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='geo',
            name='lng',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='myapp.company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.CharField(),
        ),
    ]
