# Generated by Django 5.0.7 on 2024-08-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_user_album_userid_rename_user_post_userid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='thumbnailUrl',
            field=models.CharField(max_length=200),
        ),
    ]
